baseurl:              /
source:               .
destination:          ./_site
layouts:              ./_layouts
pygments:             true
relative_permalinks:  false
permalink:            /news/:year/:month/:day/:title
