baseurl:              http://help.bmserp.com
source:               .
destination:          ./_site
layouts:              ./_layouts
highlighter:          rouge
relative_permalinks:  false
permalink:            /news/:year/:month/:day/:title
