---
title: BMS Support
timezone: Australia/Sydney

# Where things are
baseurl: http://help.bmserp.com
source: .
destination: ./_site
layouts_dir: ./_layouts
includes_dir: ./_includes

collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page

# Conversion
highlighter: rouge

# Outputting
permalink: pretty
